### ISSUE TITLE
RDRAND

### ISSUE THREAD

**Issue by chpatrick** [TomMD/entropy#30]
Hi Tom, 

Are you sure that xoring with RDRAND is a good idea? As far as I know, the system entropy sources use it anyway (in a safe manner) if it's available. Also, there are concerns about its security as it's impossible to audit - and it's has been shown that a backdoor could compromise an rng if it's mixed in incorrectly. So, it seems that just XORing it is ineffective at best and dangerous at worst. As an added benefit, if it's left out the library can be pure Haskell with no need for cbits, which is definitely good for a library with crypto applications. 

What do you think?

**Comment by TomMD** [comment]
@chpatrick Thanks for the well-reasoned report.  As you might know, this issue comes up from time to time in forms ranging from the well thought out such as yours (thanks) to the ad hominem.  I'll respond to your points one by one for sake of clarify of thought process but I'm not meaning to convince your or anyone else that they are "wrong" and should change their mind.

As a library author I'm not assuming the OS rng mixes in RDRAND or any other HWRNG.  Backdoors are a constant concern for entropy sources and are certainly possible. While RDRAND is hard to audit it is feasible for nation states or larger organizations and Intel would probably be a much smaller company if caught doing something untold.  Combining sources mitigates a large number of both mistakes as well as modes of attack for the cost of trusting the hardware already being ran. Note that, at last check, Linux's combination routine was XOR.  Even if RDRAND is left out for *nix and Windows, I'd include it for the HaLVM (which has no other information-theoretic source).

I certainly understand taking your entropy seriously and in the past have offered, with no takers, a few possible solutions.

* Continue discussion on non-bias-able mixing such as hashing.  I'm not a huge fan of this idea since it introduces complexity far above xor, but the opportunity for discussion leave open the possibility of finding something that isn't horribly over-engineered.
* A flag that disables use of RDRAND, leaving just the system source.  People previously rejected this for practical reasons, though now that stack can depend on libraries and particular flags those reasons seem diminished.
* Exposing the generators separately `rdrand :: Int -> Maybe ByteString` and `systemrand :: Int -> ByteString`.  I'd put these in some sort of .Internal module then keep the top level functionally equivalent to its current state.
* Produce a Fortuna-like library that mixes in entropy from many sources into log-sized buckets with hashing.  I would not be the one doing this work.

**Comment by esoeylemez** [comment]
A [known exploit against RDRAND+XOR exists](https://twitter.com/defusesec/status/408975222163795969), so the current implementation is not only questionable, but practically vulnerable to anyone with control over the implementation of RDRAND.

Favourite solution: stop insisting that RDRAND is a good idea and disable its support by default. To most people it's at best useless (they have their OS PRNG, so the XOR loop is just additional cost) and enforces an *unnecessary* trust assumption with zero return on investment. For the narrow space of legitimate use cases, there is nothing wrong with an off-by-default flag to enable it.

**Comment by TomMD** [comment]
@esoeylemez As I said, feasibility of a backdoor (which the link shows) is not in question either in software or hardware or software pretending to be hardware as linked.

**Comment by esoeylemez** [comment]
Investment:

  * we have to trust Intel and probably other entities as well,
  * we pay an additional XOR loop of CPU time.

Return: zero. The OS PRNG is already trustworthy and most likely already includes RDRAND mixed securely. There is absolutely no point whatsoever in using RDRAND this way. It's an investment with zero return. Period.

You're arguing with hand-wavy arguments that we should trust Intel, because you think they have no *inclination* to backdoor RDRAND. Even if that's true, the investment is still at zero return. And that's just under the trustworthiness assumption that I do *not* agree with.

**Comment by chpatrick** [comment]
@TomMD Thanks for your detailed response!

I understand now how RDRAND is necessary on HaLVM. However, I would really like it if the best practice was followed in all cases, and on systems that have a high quality entropy source available (Linux, Windows, BSD) I believe the best practice is to just use it. As a library user, I feel quite uncomfortable with a package doing something custom on top of that, even with the best of intentions. `/dev/urandom` is quite well understood, strongly recommended and requires no low-level code to use from Haskell.

Do you think it would be possible to default to just the system RNG when it's high quality, and use RDRAND when there's good no alternative (eg. on HaLVM, as you said)? I'd be happy to make a PR.

**Comment by TomMD** [comment]
@esoeylemez We can't really call xor much of a cost and I'm not even sure is measurable, but would be interested in any numbers. We do _continue_ to trust Intel/AMD and yes in a different fashion.  A return is preventing APT behaviors that include compromising distributions' RNGs or installations - I don't see anyone verifying their kernel or other software after getting a new system, when installing a new distribution, or periodically throughout use.  In short, I worry more about the software permitting mass surveillance than the hardware.  WRT targeted attacks, if you're worried about a custom chip and supply chain attack then I'd love to hear about it but am pessimistic that we can do much against such an adversary.

One method to change my mind is to argue convincingly that a software backdoor is less likely than a hardware backdoor.  Another method is to argue a change is in the best interest of the community, which I do reflect on from time to time including right now.

**Comment by TomMD** [comment]
@chpatrick I'm not inclined to disable RDRAND by default for reasons mentioned above.  I'll ponder this thread as I work today (fair notice: I'm going to go dark and get work projects done for a bit).  One last point, I find calling XOR of entropy streams "custom" is somewhat humorous as that's a wide spread strategy.

**Comment by chpatrick** [comment]
@TomMD The thing is, if I see some code that just reads from `/dev/urandom`, I'm happy because I trust the kernel developers. If I see some unaudited (?) code that does some low-level C stuff and inline assembly magic to perform an enhancement that other projects such as PGP don't deem necessary, it seems custom to me.

**Comment by esoeylemez** [comment]
I propose that we settle on a solution that uses RDRAND entropy in a least-assumptions fashion: hash the output of RDRAND and xor the hash with the output of the system RNG. An alternative solution would be to fork.

**Comment by TomMD** [comment]
@esoeylemez The hash option is one that I'm up for discussing.  The fork option is something I hope to avoid not so much for ego as for the sake of not fracturing the Haskell community even more - Vincent and my libraries already do that quite well to the point I'm likely to retire crypto-api for the sake of unity.

**Comment by chpatrick** [comment]
@esoeylemez Why is that better than leaving it out altogether? It still needs the low-level cbits and still isn't more secure than the system RNG.

**Comment by esoeylemez** [comment]
@chpatrick: XOR is a group operation, so if RDRAND is indeed backdoored and has access to the program's memory, it can produce inverses. Passing its output through a hash function would require that it performs a preimage attack.

I'm not entirely happy with the hash solution, precisely because of the extra complexity, but it's a common ground.

**Comment by chpatrick** [comment]
@esoeylemez: If it has access to your program's memory, you've already lost. :smile: What I'm proposing is neither XOR or hashing, but just using `/dev/urandom` or whatever the system provides.

**Comment by esoeylemez** [comment]
It's highly unlikely to have a backdoored RDRAND that does *not* have access to your program's memory. ;)

But the most likely way an RDRAND backdoor would be implemented is for it to be triggered by a certain value in a certain register and then have it produce the exact inverse of a certain buffer. The hash makes this attack impossible, *even with* a backdoored RDRAND (with the rationale that any backdoor would probably have to be a generic, mass-produced one).

**Comment by chpatrick** [comment]
@esoeylemez OK, so why use RDRAND at all and not just regular `/dev/urandom`?

**Comment by esoeylemez** [comment]
As said, I'd prefer to do that, but TomMD would not, so I'm proposing the hashed variant as a common ground. The only other alternative seems to be to fork, because we do not agree on base security assumptions.

**Comment by TomMD** [comment]
Happy new year!  You now have separate access to hardware and system random sources in entropy.

I needed a pure access to RDRAND, felt a bit like I was squatting a "System" named module with higher level operations, and frankly am worried that the community will fork/fragment over what I consider an esoteric argument.  SO!  See [the new entropy package](https://hackage.haskell.org/package/entropy-0.4) and, if you are interested, [the commit](https://github.com/TomMD/entropy/commit/16309d3134fdc39af71f7121432f5078290a883e) that sort of re-caps my view in an effort to keep things transparent while making an important change.

As always, continued dialog and patches are welcome.  Heads up: once `getrandom` becomes more wide spread I would expect another change from `urandom` to using `getrandom` on supported platforms.
